{
 "title": "אימונים לפי מתאמן",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player",
    "label": "Choose Trainee",
    "query": "SELECT DISTINCT name FROM PlayerStats"
   }
  ]
 },
 "panels": [
  {
   "title": "אימונים לפי מתאמן",
   "type": "table",
   "gridPos": { "h": 23, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%Y %H:%M', date) AS תאריך, date AS raw_date\nFROM PlayerStats \nWHERE name = 'or'\nORDER BY date DESC",
     "rawQueryText": "SELECT strftime('%Y-%m-%Y %H:%M', date) AS תאריך, date AS raw_date\nFROM PlayerStats \nWHERE name = '$player'\nORDER BY date DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "זמן הטסה ממוצע",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT AVG(timeInMs) AS 'זמן הטסה ממוצע'\nFROM PlayerStats\nWHERE name='or';",
     "rawQueryText": "SELECT AVG(timeInMs) AS 'זמן הטסה ממוצע'\nFROM PlayerStats\nWHERE name='$player';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "ציון הטסה",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT (CAST(NumberOfPassedRings AS FLOAT) * 100) / CAST(TotalNumberOfRings AS FLOAT) as ציון, strftime('%Y-%m-%Y %H:%M', date) AS תאריך\nFROM PlayerStats \nWHERE name = 'or'",
     "rawQueryText": "SELECT (CAST(NumberOfPassedRings AS FLOAT) * 100) / CAST(TotalNumberOfRings AS FLOAT) as ציון, strftime('%Y-%m-%Y %H:%M', date) AS תאריך\nFROM PlayerStats \nWHERE name = '$player'",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "זמני תעופה",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT date, timeInMs\nFROM PlayerStats \nWHERE name = '$player'\n",
     "rawQueryText": "SELECT date, timeInMs\nFROM PlayerStats \nWHERE name = '$player'\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}